config/routes.rb
Rails.application.routes.draw do
  resources :contents
  devise_for :users
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about' => 'pages#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/content.rb
class Content < ApplicationRecord
    belongs_to :user

    has_one_attached :image
    has_many :sales

end

app/models/sale.rb
class Sale < ApplicationRecord
    before_create : generate_guid
    belongs_to :content

    private
        def generate_guid
            self.guid =  SecureRandom.uuid()
        end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
         has_many :contents
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :set_content, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :check_user, only: [:edit, :update, :destroy]


  # GET /contents or /contents.json
  def index
    @contents = Content.all
  end

  # GET /contents/1 or /contents/1.json
  def show
  end

  # GET /contents/new
  def new
    @content = current_user.contents.build
  end

  # GET /contents/1/edit
  def edit
  end

  # POST /contents or /contents.json
  def create
    @content = current_user.contents.build(content_params)

    respond_to do |format|
      if @content.save
        format.html { redirect_to content_url(@content), notice: "Content was successfully created." }
        format.json { render :show, status: :created, location: @content }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contents/1 or /contents/1.json
  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to content_url(@content), notice: "Content was successfully updated." }
        format.json { render :show, status: :ok, location: @content }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contents/1 or /contents/1.json
  def destroy
    @content.destroy

    respond_to do |format|
      format.html { redirect_to contents_url, notice: "Content was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_content
      @content = Content.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def content_params
      params.require(:content).permit(:titolo, :descrizione, :price, :image)
    end

    def check_user
      if current_user != @content.user 
        redirect_to root_url, alert: "Scusa ma non hai accesso a questa pagina"
      end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contents/_content.html.erb
<div id="<%= dom_id content %>">
  <% if content.image.attached? %>
    <%= image_tag content.image %>
  <% end %>
  <p>
    <strong>Titolo:</strong>
    <%= content.titolo %>
  </p>
  <p>
    <strong>Descrizione:</strong>
    <%= content.descrizione %>
  </p>
  <p>
    <strong>Price (minimo 50 cents):</strong>
    <%= content.price %>
  </p>
</div>

app/views/contents/_form.html.erb
<%= form_with(model: content) do |form| %>
  <% if content.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(content.errors.count, "error") %> prohibited this content from being saved:</h2>
      <ul>
        <% content.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :titolo, style: "display: block" %>
    <%= form.text_field :titolo %>
  </div>
  <div>
    <%= form.label :descrizione, style: "display: block" %>
    <%= form.text_area :descrizione %>
  </div>
  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>
  <div>
    <%= form.label :cover, style: "display: block" %>
    <%= form.file_field :image %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/contents/edit.html.erb
<h1>Editing content</h1>

<%= render "form", content: @content %>

<br>

<div>
  <%= link_to "Show this content", @content %> |
  <%= link_to "Back to contents", contents_path %>
</div>

app/views/contents/index.html.erb
<p style="color: green"><%= notice %></p>
<h1>Contents</h1>
<table>
  <thead>
    <tr>
      <th>Immagine</th>
      <th>Titolo</th>
      <th>Descrizione</th>
      <th>Utente</th>
      <th>Prezzo</th>
    </tr>
  </thead>
  <tbody>
    <% @contents.each do |content| %>
      <tr>
        <td> <% if content.image.attached? %>
            <%= image_tag content.image, class: "thumbnail" %>
          <% end %></td>
        <td><%= content.titolo %></td>
        <td><%= content.descrizione %></td>
        <td><%= content.user.name if content.user %></td>
        <td><%= content.price %></td>
        <td><%= link_to 'Mostra', content_path(content) %></td>
        <%if content.user == current_user %>
          <td><%= link_to 'Edit', edit_content_path(content) %></td>
          <td><%= link_to 'Destroy', content_path(content), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to "New content", new_content_path %>

app/views/contents/new.html.erb
<h1>New content</h1>

<%= render "form", content: @content %>

<br>

<div>
  <%= link_to "Back to contents", contents_path %>
</div>

app/views/contents/show.html.erb
<p style="color: green"><%= notice %></p>
<%= render @content %>
<div>
  <%= link_to "Edit this content", edit_content_path(@content) %> |
  <%= link_to "Back to contents", contents_path %>
  <%= button_to "Destroy this content", @content, method: :delete %>
</div>

app/views/layouts/_footer.html.erb
<footer class="page-footer blue-grey darken-2">
  <div class="footer-copyright">
    <div class="container">
      <div class="row">
        <div class="col s4"> © 2023 Lacerba.io</div>
        <div class="col s4">Social</div>
        <div class="col s4">
          <%= link_to "About", about_path, class: "grey-text text-lighten-4 right" %>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar">
  <nav class="blue-grey darken-2">
    <div class="container nav-wrapper">
      <%= link_to "LacerMarket", root_path, class: "brand-logo" %>
      <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
      <ul class="right hide-on-med-and-down">
        <% if user_signed_in? %>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Log In",  new_user_session_path %></li>
          <li><%= link_to "Registrazione",  new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </nav>
  <ul class="sidenav" id="mobile-demo">
    <% if user_signed_in? %>
      <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
    <% else %>
      <li><%= link_to "Log In",  new_user_session_path %></li>
      <li><%= link_to "Registrazione",  new_user_registration_path %></li>
    <% end %>
  </ul>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LacerMarket</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>
  <body>
    <%= render "layouts/header" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <main class="container">
      <%= yield %>
    </main>
    <%= render "layouts/footer" %>
  </body>
  <script>
    document.addEventListener('DOMContentLoaded', function() {
     var elems = document.querySelectorAll('.sidenav');
     var instances = M.Sidenav.init(elems);
      });
  </script>
</html>

app/views/pages/about.html.erb
<h1>About us</h1>
<p>We are a small company based in Ruby on Rails.</p>

app/views/pages/home.html.erb
<h1>Welcome to my app!</h1>
<p>This is the home page.</p>
<a class="waves-effect waves-light btn">button</a>
<a class="waves-effect waves-light btn"><i class="material-icons left">cloud</i>button</a>
<a class="waves-effect waves-light btn"><i class="material-icons right">cloud</i>button</a>